import ImageCard from "./ImageCard";

const NorisTransform = () => {
    return (
    <div className="container">
    <div className="components">
        <h1 id="noriastransform" className="title">Noria’s Transform</h1>

        <h2 className="subtitle">Hama Grows</h2>
            <p>
            The Orontes Valley forms a boundary between the deserts of Syria and the mountains to the west, placing Hama at the center of the wet/dry farming zone. With its fertile terra rossa soil and the Orontes River, Hama was in a prime position for economic growth. The norias ensured a consistent water supply and the irrigation of crops, even during the hostile dry season, making them a matter of life and death <em>(NMOD; Bartl 2; UW).</em>
            </p>
            <ImageCard figure="3.1"/>
            <p>In the Early to Late Bronze Age <em>(2400&ndash;1200 BCE)</em>, continuously occupied settlements were found along the banks of the Orontes. However, during the Iron Age <em>(1200&ndash;333 BCE)</em>, there was a decline in the number of settlements <em>(Bartl 16&ndash;18)</em>. Then, during the Hellenistic period <em>(300&ndash;50 BCE)</em>, new and renewed settlements began to emerge. This correlates with the first evidence of sāqiya and treadwheels (animal- and human-powered waterwheels) dated to 300&ndash;10 BCE. The structures of this period were associated with agriculture, transforming the arid landscape into one that could flourish <em>(Wilson 1&ndash;30)</em>.
            </p>
            <p>During the Roman and Early Byzantine periods <em>(65 BCE&ndash;636 CE)</em>, the area was free of political strife, creating a time of peace and development, which marked the era of highest settlement density <em>(Bartl 19)</em>. In the Roman era, norias came into mainstream use, driving agriculture and, in turn, the economy, which created an enriched and thriving population <em>(Wilson 9; Chambrade).</em>
            </p>
            <ImageCard figure="3.2"/>
        <h2 className="subtitle">Innovation</h2>
            <p>With the noria drawing its power directly from the water, it can move vast amounts of water without relying on animal or human labor. This surplus water could then be used for fountains and technological developments <em>(see Figures 3.3&ndash;3.5).</em>
            </p>
            <p>During the medieval period, there was an increase in references to norias in geographical writings, indicating their significance and continuous development <em>(Hafian)</em>. As Hama's population grew, norias spread throughout the region, with a total of 90 documented. Of these, 50 were still operational and supplying water in the early 1900s. However, their numbers dwindled due to natural disasters and war, and today, only 14 remain standing <em>(NMOD).</em>
            </p>
            <p>Tinkers found ways to use the excess power generated by norias to develop novel devices, such as the first known suction pump and the water clock. The water clock utilized valves and hydraulic controls to track not only the time of day but also the seasons and the signs of the Zodiac <em>(see Fig. 3.4) (Hill 102&ndash;105).</em>
            </p>
            <ImageCard figure="3.3"/>
            <ImageCard figure="3.4"/>
            <ImageCard figure="3.5"/>
        <h2 className="subtitle">Culture</h2>
            <p>With the enormous impact that the norias had on the development of Hama, they have influenced both local and global culture. Known as the "City of Wheels," Hama has become a hub for tourism, while the norias themselves have achieved recognition as engineering landmarks, further inspiring video games and artwork.
            </p>
        <h3 className="subheading">Recreation</h3>
            <p>
                The dams of the noria, forming convenient swimming pools, and the revolving wheel, acting as an elevator, made the noria a source of recreation to cool off during the summer. {" "}
                <a
                href="https://youtu.be/XI2AZnS7J7s?si=0jhnx23816dVZep5"
                target="_blank"
                rel="noopener noreferrer"
                >
                People rode the noria
                </a>
                , using it as a unique diving platform, while the less adventurous waded in the surrounding water, washed clothes, or went fishing <em>(see Figs. 1.3, 4.1, and 4.2).</em>
            </p>
            <ImageCard figure="4.1"/>
            <ImageCard figure="4.2"/>
        <h3 className="subheading">Art</h3>
        <p>The influence of the water wheels was not only practical but also artistic. While on an expedition to Hama, architect Ejnar Leo Fugmann was inspired by the norias and painted around 100 watercolors of Hama and its water wheels <em>(see Figs. 4.3 and 4.4) (NMOD)</em>. The norias have also inspired poets, as seen in Considerations about the Dolab-nama, where T&uuml;rkan has collected poems inspired by water wheels. I have translated one such poem, shown in Figure 4.5.</p>
        <p>
            T&uuml;rkan also writes the following passage, highlighting the reputation the norias have established:
            </p>
        <blockquote className="highlight">
        The waterwheel has become an indispensable classic for Turkish poets because it turns slowly, making sounds similar to crying. In these poems, the lover identifies himself as a waterwheel. The love and the screams of the lover with the feeling of staying apart from their beloved are similar to the groans heard from far away Dolab-nama also means the verse in question from the language of the water closet with the question, “Expressing the chant of love of Allah.” Moreover, the insufficient definition of the dolab-nama was emphasized (Alvan
            443)
        </blockquote>

        <div className="poem-container">
            <p className="poem">
            <h3 className="poem-title">The Ode of the Water Wheel</h3>
            Today, I questioned a water wheel,
            <br />
            I asked, "Why do you turn upon this stream?"
            <br />
            <br />
            "Why is your chest pierced, your eyes full of tears,
            <br />
            What causes you to lament with such reproach?"
            <br />
            <br />
            "You have no rest, turning day and night,
            <br />
            Pouring blood-stained tears from sorrowful eyes."
                <br />
            <br />
            "Your straight stature has bent like a bow,
            <br />
            Your groaning has become a melody for the rebab."
            <br />
            <br />
            "In the morning, your tears flow endlessly,
            <br />
            You do not find a moment’s sleep at night."
            <br />
            <br />
            "Why do you cry out in anguish and pain,
            <br />
            Is your sorrow beyond measure or account?"
                <br />
            <br />
            "Your grieving chest has been pierced by groans,
            <br />
            Your sighs have turned hearts into burning embers."
                <br />
            <br />
            "What news has fate delivered to you,
            <br />
            That your ledger of grief could not fit into books?"
                <br />
            <br />
            "What cruelty has this tyrannical wheel inflicted on you,
            <br />
            That you’ve fallen into this endless reproach?"
                <br />
            <br />
            "Your smoke has darkened the blue skies above,
            <br />
            And your sighs have turned the earth into dust below."
                <br />
            <br />
            I asked about the water wheel’s endless turning,
            <br />
            And as it turned, the wheel gave me its reply.
            </p>
        </div>
        <ImageCard figure="4.3"/>
        <ImageCard figure="4.4"/>


        <h3 className="subheading">Tourism</h3>
            <p>
            Tourism is also driven by the noria. In 2006, Noria al-Muhammadiyya was listed as an engineering landmark{" "}
                <em>(ASME 10)</em>, solidifying its status as a cultural icon of Syria that attracts tourists to admire its beauty. Next to some of the norias are cafes where tourists can relax and enjoy a delicious meal (see{" "}
                <a
                href="https://maps.app.goo.gl/6va9VrNJ9UPzyrQf6"
                target="_blank"
                rel="noopener noreferrer"
                >
                Cafe with Noria Table Side
                </a>{" "}
                and{" "}
                <a
                href="https://maps.app.goo.gl/wSz7rSnj2h98Ty8A7"
                target="_blank"
                rel="noopener noreferrer"
                >
                Video of Cafe
                </a>
                ).
            </p>

        <h3 className="subheading">Video Games</h3>
            <p>
            The impact of the norias extends even into video games, where their iconic wooden structures captivate creators. With their timeless aesthetic, norias are ideal for world-building games such as  <em>Anno 1404</em> and{" "}
                <em>Kingdoms and Castles</em>, each featuring norias in their gameplay <em>(see Fig. 4.6) (Anno 1404 Wiki;
                Elreyboro).</em>
            </p>
        <ImageCard figure="4.5"/>
        <ImageCard figure="4.6"/>
        </div>
    </div>
);
};

export default NorisTransform;
