const WorksCited = () => {
  return (
    <div id="workcited" className="works-cited-container">
      <h2 className="title">Works Cited</h2>
      <div className="works-cited">
        <p>Alvan, T&uuml;rkan. &ldquo;The Considerations about the Dolab-nama Genre in Classical Turkish Poetry.&rdquo; <em>Journal of Turkish Language and Literature</em>, vol. 60, no. 2, 2020, pp. 443-476. <em>EBSCOhost</em>, <a href="https://doi.org/10.26650/TUDED2020-0031">https://doi.org/10.26650/TUDED2020-0031</a>.</p>
        <p>American Society of Mechanical Engineers. "Noria al-Muhammadiyya: Historic Mechanical Engineering Landmark."<em> ASME, </em>Dec. 2006, <a href="https://www.asme.org/wwwasmeorg/media/resourcefiles/aboutasme/who%20we%20are/engineering%20history/landmarks/241-noria-al-muhammadiyya.pdf"><em>https://www.asme.org/wwwasmeorg/media/resourcefiles/aboutasme/who%20we%20are/engineering%20history/landmarks/241-noria-al-muhammadiyya.pdf</em></a><em>.</em></p>
        <p>&ldquo;Anno 1404 Wiki: Noria.&rdquo; <em>Fandom, </em><a href="https://anno1404.fandom.com/wiki/Noria"><em>https://anno1404.fandom.com/wiki/Noria</em></a></p>
        <p>&ldquo;Al Muhammadiya Noria.&rdquo; <em>Archnet, </em><a href="https://www.archnet.org/sites/21020"><em>https://www.archnet.org/sites/21020</em></a></p>
        <p>Astour, Michael C. &ldquo;Tunip-Hamath and Its Region: A Contribution to the Historical Geography of Central Syria.&rdquo;<em> Orientalia,</em> vol. 46, no. 1, 1977, pp. 51&ndash;64<em>. JSTOR, </em><a href="http://www.jstor.org/stable/43074742"><em>http://www.jstor.org/stable/43074742</em></a><em>.</em></p>
        <p>Bartl, Karin, and Michel al-Maqdissi. "Archaeological Survey in the Hama Region 2003&ndash;2005." <em>Syria</em>, vol. HS IV, 2016. <em>OpenEdition Journals</em>, 1 Dec. 2018, <a href="http://journals.openedition.org/syria/5107"><em>http://journals.openedition.org/syria/5107</em></a><em>.</em></p>
        <p>Boyer, David S. &ldquo;A Young Syrian Makes a Daredevil Leap; Another Rides Hama&rsquo;s Might Water Wheel.&rdquo;<em> Internet Archive, </em>National Geographic, vol. 6, no. 6, Dec. 1954, pp. 819<em>. Internet Archive, </em><a href="https://archive.org/details/jishankhan_hotmail_1954/1954-12/page/n99/mode/2up"><em>https://archive.org/details/jishankhan_hotmail_1954/1954-12/page/n99/mode/2up</em></a><em>.</em></p>
        <p>Chambrade, Marie-Laure and Myriam Saad&eacute;-Sbeih. "Les roues hydrauliques du Proche-Orient: Lieux, techniques et usages."<em> Arch&eacute;Orient &ndash; Le Blog,</em> 17 April 2015, <a href="https://archeorient.hypotheses.org/3936"><em>https://archeorient.hypotheses.org/3936</em></a><em>.</em></p>
        <p>de Miranda, A. "Aesthetic Tradition and Ancient Technology: A Case Study of the Water-Wheel."<em> Design and Nature II, </em>edited by M. W. Collins and C. A. Brebbia<em>, </em>vol. 73, 2004, pp. 105-114. <em>WitPress, </em><a href="https://www.witpress.com/Secure/elibrary/papers/DN04/DN04011FU.pdf"><em>https://www.witpress.com/Secure/elibrary/papers/DN04/DN04011FU.pdf</em></a><em>.</em></p>
        <p>Dick, Harris Brisbane. "Hama (Syria): View of water wheel on the Orontes River." <em>The Metropolitan Museum of Art (MMOA),</em> 1943, <a href="https://libmma.contentdm.oclc.org/digital/collection/p16028coll11/id/5249">https://libmma.contentdm.oclc.org/digital/collection/p16028coll11/id/5249</a>.</p>
        <p>Dick, Harris Brisbane. "Hama (Syria): View of Water Wheels on the Orontes River." T<em>he Metropolitan Museum of Art (MMOA),</em> 1943, <a href="https://libmma.contentdm.oclc.org/digital/collection/p16028coll11/id/5243">https://libmma.contentdm.oclc.org/digital/collection/p16028coll11/id/5243</a>.</p>
        <p>Dick, Harris Brisbane. &ldquo;Hama (Syria): view of water wheels and aquaduct along the Orontes River.&rdquo; <em>The Metropolitan Museum of Art (MMOA), 1</em>943, <a href="https://libmma.contentdm.oclc.org/digital/collection/p16028coll11/id/5273">https://libmma.contentdm.oclc.org/digital/collection/p16028coll11/id/5273</a>.</p>
        <p>Elreyboro. &ldquo;Kingdoms and Castles: Noria-The water mover.&rdquo; <em>Steam Community</em>, 3 July 2019, <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=1790816488\">https://steamcommunity.com/sharedfiles/filedetails/?id=1790816488</a>.</p>
        <p>Hafian, Wa'al. "Discover Islamic Art: Norias (Nawa&rsquo;ir) of Hama.&rdquo;<em> Museum With No Frontiers</em>, 2024, <a href="https://islamicart.museumwnf.org/database_item.php?id=monuments;ISL;sy;Mon01;32;en."><em>https://islamicart.museumwnf.org/database_item.php?id=monuments;ISL;sy;Mon01;32;en</em></a><em>.</em></p>
        <p>Hafian, Wa'al. "Noria al-Kudhra, al-Dawalik and al-Dasha (Hama, Syria)."<em> Museum With No Frontiers, </em>2024<em>, </em><a href="https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-966/lan-en"><em>https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-966/lan-en</em></a><em>.</em></p>
        <p>Hafian, Wa'al. "Noria al-Muhammadiyya(Hama, Syria)."<em> Museum With No Frontiers, 2024, </em><a href="https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-1197/lan-en"><em>https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-1197/lan-en</em></a><em>.</em></p>
        <p>Hafian, Wa'al. "Noria Ja&lsquo;bariyya, Sahuniyya, and Kilaniyya(Hama, Syria)."<em> Museum With No Frontiers, </em>2024<em>, </em><a href="https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-1198/lan-en"><em>https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-1198/lan-en</em></a><em>.</em></p>
        <p>Hafian, Wa'al. "Noria Jisriyya and Ma&lsquo;muriyya(Hama, Syria)."<em> Museum With No Frontiers, </em>2024<em>, </em><a href="https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-1199/lan-en"><em>https://explore.museumwnf.org/themes/t-1/c-sy/l-185/m-1199/lan-en</em></a><em>.</em></p>
        <p>Hill, Donald R. &ldquo;Mechanical Engineering in the Medieval Near East.&rdquo;<em> Scientific American,</em> vol. 264, no. 5, 1991, pp. 100&ndash;05.<em> JSTOR, </em><a href="https://www.jstor.org/stable/24936907"><em>https://www.jstor.org/stable/24936907</em></a><em>.</em></p>
        <p>Institut Fran&ccedil;ais Du Proche-Orient (ifpo), Arm&eacute;e Du Levant. Syria, Hama Governorate, Tell Hama, oblique aerial view. Photography, MEAE - CNRS UMIFRE 6 - USR 3135, Hama, Syria. 24 April 1936. <a href="https://hal.science/hal-02443606v1.">https://hal.science/hal-02443606v1</a>.</p>
        <p>Laess&oslash;e, J&oslash;rgen. &ldquo;Reflexions on Modern and Ancient Oriental Water Works.&rdquo; <em>Journal of Cuneiform Studies</em>, vol. 7, no. 1, 1953, pp. 5&ndash;26. <em>EBSCOhost</em>, <a href="https://doi.org/10.2307/1359477">https://doi.org/10.2307/1359477</a>.</p>
        <p>National Museum of Denmark. "Life in an Ancient Near Eastern Town."<em> NMOD,</em> <a href="https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/life-in-an-ancient-near-eastern-town/"><em>https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/life-in-an-ancient-near-eastern-town/</em></a><em>.</em></p>
        <p>National Museum of Denmark. "The Water Wheels of Hama." <em>NMOD,</em> <a href="https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/the-water-wheels-of-hama/">https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/the-water-wheels-of-hama/</a>.</p>
        <p>National Museum of Denmark. "Hama in the 1930s" <em>NMOD,</em> <a href="https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/hama-in-the-1930s/">https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/hama-in-the-1930s/</a>.</p>
        <p>National Museum of Denmark. "Watercolours of Hama in the 1930s" <em>NMOD,</em> <a href="https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/watercolours-of-hama-in-the-1930s/">https://en.natmus.dk/historical-knowledge/historical-knowledge-the-world/the-lands-of-the-mediterranean/the-far-east/digital-hama-a-window-on-syrias-past/watercolours-of-hama-in-the-1930s/</a>.</p>
        <p>Stevenson, D. W. W. &ldquo;A Proposal for the Irrigation of the Hanging Gardens of Babylon.&rdquo;<em> Iraq, </em>vol. 54, 1992, pp. 35&ndash;55<em>. EBSCOhost, </em><a href="https://doi.org/10.2307/4200351"><em>https://doi.org/10.2307/4200351</em></a><em>.</em></p>
        <p>University of Warsaw (UW)<em>.</em> "Discovery of Oldest Representation of a Water Wheel on a Roman Mosaic from Apamea." <em>University of Warsaw, </em><a href="https://en.uw.edu.pl/discovery-of-oldest-representation-of-a-water-wheel-on-a-roman-mosaic-from-apamea/#lightbox[galleryid-27169-1]/0/"><em>https://en.uw.edu.pl/discovery-of-oldest-representation-of-a-water-wheel-on-a-roman-mosaic-from-apamea/#lightbox[galleryid-27169-1]/0/</em></a><em>.</em></p>
        <p>"Waterwheel in Syria."<em> Alternative Energy, </em>edited by K. Lee Lerner, et al., 2nd ed., UXL, 2012. <em>Gale In Context: Science, </em><a href="https://link.gale.com/apps/doc/PC4205137010/SCIC?u=ncc_paul&amp;sid=ebsco&amp;xid=efe45fc5"><em>link.gale.com/apps/doc/PC4205137010/SCIC?u=ncc_paul&amp;sid=ebsco&amp;xid=efe45fc5</em></a><em>.</em></p>
        <p>Wilson, Andrew. &ldquo;Machines, Power and the Ancient Economy.&rdquo; <em>The Journal of Roman Studies</em>, vol. 92, 2002, pp. 1&ndash;32. <em>EBSCOhost</em>, <a href="https://doi.org/10.2307/3184857">https://doi.org/10.2307/3184857</a>.</p>
      </div>
    </div>
  );
};

export default WorksCited;
